language: ruby
rvm:
- 2.2.2
before_install: gem install bundler -v 1.10.5
env:
  global:
    - AWS_DEFAULT_REGION=us-east-1
    - FAKE_AWS_SDK_TEST_BUCKET=fake-aws-sdk-s3-test
  matrix:
    - secure: cuFj0+Ca3vL9/SE+FLm8gfaKOFyGVjY3zFcx7zqJ4dl1AiGM8mbl0SzV0tG+7Zvtrg+MnEl0I1TGaAyfGzNAbt+akue46h/fahhHGAMaR1Xi/3cwgjvderfZfRkDi57Vp8A+UD9PkNvFZRmpCpbBL/LpEBdRW4vWkIxENoCurJeKwIzLaaP/pHPA207eqbePUN8OF4WRHRBGXdAFAZq3SpuNZws4JE4yCPPivQh3p29eIcURPvgbB76tS+GfiAkfFqakuMBW/2EFA5RnZ0VqN5ORKgA2G7hjMDQfv+nx4bYrju+VG/c0gPMFOJfC3oezsEzWT6HjYRRBqtcmJ4xDoVVVXm6XOshhg9ukoPEpxgBNSmk3v6v8lbxHFMxNNFR6EyGHzEKHK0Ng/dfDlnu2v8jLhDGW0nNbZX4bxhjOtMcQmqe0SMWktYtHleKRk1DHPDwWYFsa/Kw808UPM2NK0asqowDxE8DdKLnPkZpXVl+f1hobPhodH3oX4DPFu/gyIvEzwYgGvOLEmNYXEZfpA58AKfe9yUm2Bvg2+LYLR2xIVkn7FAIJ+8s9kbIgr+19i234xspi9ZyO1JxAo1c8pVY6k1MmzembgulqfuiJSutEOXuAopVszUgOZtVD7O9yonFgyeNxlCTB1X8n2EC35JG73RNHLTwRcA0LTBq0PtQ=
